pipeline {
     agent {
          docker {
               image 'node:alpine' 
               args '-p 33333:9000' 
          }
     }
     environment {
          HOME = '.'
     }
     stages {
          stage('Source') {
               steps {
                    git branch: 'main',
                        url: 'https://github.com/Winternight9/dota2-analysis-software-process-project-2020.git'
               }
          }
          stage('Build') {
               steps {
                    sh 'npm install'
               }
          }
          stage('Test') {
               steps {
                    echo 'testing...'
               }
          }
          stage('Deploy') {
               steps {
                    sh './api/dota2/jenkins/scripts/deliver.sh'
                    input message: 'Finished using the web site? (Click "Proceed" to continue)'
                    sh './api/dota2/jenkins/scripts/kill.sh'
               }
          }
     }
}
